version: '3.1'
services:
  mysql:
    container_name: mysql
    ports:
      - '3308:3308'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: lawa
      MYSQL_ROOT_PASSWORD: lawa
    volumes:
      - mysql:/var/lib/mysql
  frontend:
    container_name: lawa-app
    ports:
      - '3000:3000'
    build:
      dockerfile: Dockerfile
    volumes:
      - ./lawa-app:/src
      - /lawa-app/node_modules
      - /lawa-app/.next

volumes: #define our mysql volume used above
  mysql: